import express from 'express'; import {WebSocketServer} from 'ws'; import http from 'http'; import fs from 'fs';
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server,path:'/voice'}),PORT=process.env.PORT||10000,F='./data/database.json'; let db=JSON.parse(fs.readFileSync(F));
const n=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,"'").replace(/\s+/g,' ').trim(); const O=id=>db.orders.find(x=>x.id===id),C=o=>db.customers.find(x=>x.id===o.customerId),P=id=>db.products.find(x=>x.id===id),T=o=>o.items.reduce((a,i)=>a+(P(i.productId)?.price||0)*i.qty,0),save=()=>fs.writeFileSync(F,JSON.stringify(db,null,2));
const list=o=>o.items.map(i=>`${P(i.productId)?.name}${i.variant?' '+i.variant:''}${i.size?' taille '+i.size:''} x${i.qty}`).join(' + ');
function intents(x){let t=n(x),a=[];if(/annul|cancel|fassakh|تلغ/.test(t))a.push('cancel');if(/apres une heure|après une heure|بعد ساعة|rappelle|عاود.*اتصل/.test(t))a.push('callback');if(/adresse|address|3onwen|عنوان/.test(t))a.push('address');if(/numero|telephone|tel|نيميرو|نمرة|تليفون/.test(t))a.push('phone');if(/prix|price|قداش|بقداش|المجموع|total/.test(t))a.push('price');if(/couleur|color|لون/.test(t))a.push('color');if(/taille|size|قياس|صغير|smol|small/.test(t))a.push('size');if(/quantite|quantity|كمية|قطعة|زوز|ثلاثة/.test(t))a.push('qty');if(/نحي|نحّي|enleve|retire|خلي.*كان|juste/.test(t))a.push('remove');if(/oui|yes|ok|okay|اي|ايه|نعم|باهي|مريقل|صحيح|exactement/.test(t))a.push('yes');if(/non|no|لا|موش|مش/.test(t))a.push('no');return a}
function phone(x){let d=(x||'').replace(/\D/g,'');return d.length>=8?d.slice(-8):null} function qty(x){let t=n(x);if(/زوز|deux|two/.test(t))return 2;if(/ثلاثة|trois|three/.test(t))return 3;let m=t.match(/\b([1-9]|10)\b/);return m?+m[1]:null}
function color(x){let t=n(x);for(const p of db.products)for(const v of p.variants)if(t.includes(n(v)))return v;if(/blanc|white|ابيض/.test(t))return'blanc';if(/noir|black|اسود/.test(t))return'noir';if(/rouge|red|احمر/.test(t))return'rouge';if(/bleu|blue|ازرق/.test(t))return'bleu';return null}
function answer(s,text){let o=O(s.orderId),c=C(o),t=n(text),i=intents(text);s.turn++;
 if(i.includes('cancel')){s.topic='cancel';return'أكيد، نجم نلغيهالك. تحب نعمل cancel نهائي للcommande؟'} if(s.topic==='cancel'){if(i.includes('yes')){o.status='CANCELLED';save();s.topic='done';return'مريقل، تلغات الـcommande. يعطيك الصحة.'}if(i.includes('no')){s.topic='general';return'باهي، نخليها كيف ما هي. شنوة تحب نراجع معاك؟'}}
 if(i.includes('callback')){s.topic='callback';return'ما فما حتى مشكل. نعاودو نتصلو بيك بعد ساعة. تحب نفس النيميرو ولا نزيدو نيميرو آخر؟'} if(s.topic==='callback'&&i.includes('phone')){let p=phone(text);if(p){c.altPhone=p;save();s.topic='general';return`مريقل، سجلت النيميرو الآخر ${p}. نعاودو نتصلو بيك بعد ساعة.`}}
 if(i.includes('price'))return`المجموع الحالي هو ${T(o)} دينار.`;
 if(i.includes('address')){s.topic='address';return`العنوان اللي عندنا هو ${c.address}. تحب تبدلو؟`} if(s.topic==='address'&&i.includes('no')){s.topic='general';return'باهي، نخليه كيف ما هو. شنوة تحب نراجع توا؟'} if(s.topic==='address'&&(i.includes('yes')||text.length>10)){s.topic='address_new';return'باهي، أعطيني العنوان الجديد بالتفصيل.'} if(s.topic==='address_new'){c.address=text.trim();save();s.topic='general';return`مريقل، بدلت العنوان إلى ${c.address}. حاجة أخرى؟`}
 if(i.includes('phone')){s.topic='phone';return`النيميرو اللي عندنا هو ${c.phone}. تحب تزيد نيميرو آخر؟`} if(s.topic==='phone'){let p=phone(text);if(p){c.altPhone=p;save();s.topic='general';return`مريقل، زدت النيميرو ${p}. حاجة أخرى؟`}}
 if(i.includes('remove')){let targets=db.products.filter(p=>t.includes(n(p.name))||t.includes(n(p.name).split(' ')[0]));if(targets.length){let ids=targets.map(p=>p.id),before=o.items.length;o.items=o.items.filter(x=>!ids.includes(x.productId));if(o.items.length<before){save();return`مريقل، نحّيت ${targets.map(p=>p.name).join(' و ')} وخليتلك ${list(o)}. المجموع ولى ${T(o)} دينار. فما حاجة أخرى؟`}}}
 if(i.includes('color')){let v=color(text),x=o.items[0];if(v&&P(x.productId).variants.map(n).includes(n(v))){x.variant=v;save();return`مريقل، اللون ولى ${v}. حاجة أخرى تحب تبدلها؟`}return`الألوان الموجودة هي ${P(o.items[0].productId).variants.join(' ولا ')}.`}
 if(i.includes('qty')){let q=qty(text),x=o.items[0];if(q){x.qty=q;save();return`مريقل، ولّينا على ${q} pièces. المجموع الجديد ${T(o)} دينار.`}return'قداش تحب من قطعة؟'}
 if(i.includes('yes')&&['confirm','general'].includes(s.topic)){o.status='CONFIRMED';save();s.topic='done';return`مريقل، تأكدت الـcommande. باش توصلك على ${c.address}. يعطيك الصحة و نهارك زين.`} if(i.includes('no'))return'باهي، ما نثبت حتى شيء. شنوة تحب تبدّل ولا نراجع؟';
 if(/huawei|oppo|casque|sneakers/.test(t))return'إي، فهمتك. تحب تبدّل المنتج، الكمية، اللون، ولا نراجع بقية الـcommande؟';return'فهمتك. نجم نعاونك في produit، quantité، couleur، adresse، numéro، prix، rappel ولا annulation. شنوة تحب تعمل؟'}
app.use(express.static('public'));app.get('/health',(q,r)=>r.json({ok:true,version:'9.0.0',mode:'FREE'}));app.get('/api/orders',(q,r)=>r.json(db.orders.map(o=>({id:o.id,status:o.status,customer:C(o)?.name,total:T(o),summary:list(o)}))));app.get('/api/orders/:id',(q,r)=>{let o=O(q.params.id);if(!o)return r.status(404).json({error:'not found'});r.json({...o,customer:C(o),items:o.items.map(x=>({...x,product:P(x.productId)})),total:T(o)})});
wss.on('connection',ws=>{let s={orderId:'ORD-DEMO-MULTI',topic:'general',turn:0};ws.send(JSON.stringify({type:'ready'}));ws.on('message',raw=>{let m=JSON.parse(raw);if(m.type==='select'){s.orderId=m.orderId;s.topic='general';s.turn=0;return}if(m.type==='start'){let o=O(s.orderId),c=C(o);ws.send(JSON.stringify({type:'assistant',text:`عسلامة ${c.name.split(' ')[0]}، نكلمك بخصوص commande عملتها عندنا. فيها ${list(o)}. المجموع الحالي ${T(o)} دينار. نراجعوها مع بعضنا؟`}));return}if(m.type==='user'){let a=answer(s,String(m.text||''));ws.send(JSON.stringify({type:'user',text:m.text}));ws.send(JSON.stringify({type:'assistant',text:a}));ws.send(JSON.stringify({type:'state',state:s,order:O(s.orderId),customer:C(O(s.orderId))}))}})});server.listen(PORT,'0.0.0.0',()=>console.log('Ordely V9 on '+PORT));
